"""add_intro_shown_to_users_table

Revision ID: 5bd1bb7461d9
Revises: 305aa287a264
Create Date: 2025-03-14 03:01:39.673710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bd1bb7461d9"
down_revision: Union[str, None] = "305aa287a264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_intro_shown", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_intro_shown")
    # ### end Alembic commands ###
