"""add_area_field

Revision ID: 4debf466729a
Revises: 9edd1c380f14
Create Date: 2025-02-28 04:20:20.418170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4debf466729a"
down_revision: Union[str, None] = "9edd1c380f14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("area", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "area")
    # ### end Alembic commands ###
