"""add_indoor_room_field

Revision ID: f90b5b4482da
Revises: 4debf466729a
Create Date: 2025-02-28 04:43:09.161863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f90b5b4482da"
down_revision: Union[str, None] = "4debf466729a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("indoor_room", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "indoor_room")
    # ### end Alembic commands ###
